import:
  title: 'lovata.shopaholic::lang.product.import_title'
  modelClass: Lovata\Shopaholic\Models\Product
  redirect: lovata/shopaholic/products
  list:
    columns:
      external_id:
        label: 'lovata.toolbox::lang.field.external_id'
      active:
        label: 'lovata.toolbox::lang.field.active'
      name:
        label: 'lovata.toolbox::lang.field.name'
      code:
        label: 'lovata.toolbox::lang.field.code'
      preview_text:
        label: 'lovata.toolbox::lang.field.preview_text'
      description:
        label: 'lovata.toolbox::lang.field.description'
      preview_image:
        label: 'lovata.toolbox::lang.field.preview_image'
      images:
        label: 'lovata.toolbox::lang.field.images'
      brand_id:
        label: 'lovata.shopaholic::lang.field.brand'
      category_id:
        label: 'lovata.toolbox::lang.field.category'
      additional_category:
        label: 'lovata.shopaholic::lang.field.additional_category'

      dimentions:
        label: Габариты

      temp_condition:
        label: Темп. режим

      volume:
        label: Объем

      power:
        label: Мощность

      supply:
        label: Питание

      production:
        label: Производство

      perfomance:
        label: Производительность

      capacity:
        label: Вместимость

      gas_power:
        label: Газовая мощность

  form:
    fields:
      deactivate:
        label: 'lovata.toolbox::lang.field.import_deactivate'
        comment: 'lovata.toolbox::lang.field.import_deactivate_description'
        type: checkbox